# Use python as base image
FROM python

# Create work directory
WORKDIR /python-app

# Copy the code into the working directory 
COPY . /python-app/

# Python command for running the python code
CMD ["python", "rng.py"]